use DataWarehouseAnalytics;

--select * from information_schema.columns where table_name like '%customers%';
--Explore All countries our customers come from
select distinct country from gold.dim_customers;
--Explore the category from product
select distinct category from gold.dim_products;
select distinct category,subcategory,product_name from gold.dim_products 
order by 1,2,3
--find the date of the first and last order
--How many years of sales are available

select min(order_date) as first_order_date,max(order_date) as last_order_date ,
		datediff(year,min(order_date),max(order_date)) as years_of_sales
		from gold.fact_sales;
--Find the youngest and oldest Customers
select min(birthdate) as oldest_birthdate,
		max(birthdate) as youngest_birthddate,
		datediff(year,min(birthdate),getdate()) as oldest_age,
		datediff(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customers;
select top 10 * from gold.fact_sales;
select top 10 * from gold.dim_customers;
select top 10 * from gold.dim_products;
select top 20 * from gold.dim_products;
--Find the total sales
select sum(sales_amount) from gold.fact_sales;
--Find how many items are sold
select sum(quantity) as total_quantity  from gold.fact_sales;
--Find the average selling Price
select avg(price) as Avg_price from gold.fact_sales;
--Find the total number of the orders
select count(distinct order_number) as Total_ordders from gold.fact_sales;
--find the total number of products
select count( product_key) as Totak_Products from gold.dim_products;
--find the total number of cutomers
select count(customer_key) as Total_customers  from gold.dim_customers
--Find the customers who haved an order
select count(distinct customer_key) as Total_customers_placed_an_order FROM gold.fact_sales



--Generate a report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name ,sum(sales_amount) as measure_value from gold.fact_sales
UNION ALL
SELECT 'Total Quantity' ,sum(quantity) from gold.fact_sales
UNION ALL
SELECT 'Average Price',avg(price)  from gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders',count(distinct order_number)  from gold.fact_sales
UNION ALL
SELECT 'Total.Nr.Products',count( product_key)  from gold.dim_products
UNION ALL
SELECT 'Total Nr.Customers', count(customer_key) from gold.dim_customers
--Find total customers by countries
select country as Country ,count( customer_key)  as Total_customers from gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC
--calclaute total profit
select 
	sum(f.sales_amount-(p.cost*f.quantity)) as Total_Profit
	from gold.fact_sales f
	join gold.dim_products p
	on f.product_key=p.product_key
--Profit for each Product
SELECT
    p.product_name,
    SUM(s.sales_amount - (p.cost * s.quantity)) AS profit
FROM gold.fact_sales s
JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY profit DESC;
--Profit for each Category
SELECT
    p.category,
    SUM(s.sales_amount - (p.cost * s.quantity)) AS total_profit
FROM gold.fact_sales s
JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_profit DESC;

--find total customers by gender
SELECT 
	gender ,count(customer_key) as Total_customers
FROM gold.dim_customers
GROUP by gender
order by Total_customers desc;
--find total product by category

select
category,
count(product_key) as total_products
from gold.dim_products
where category is not null
group by category
order by total_products DESC
--what is the average costs in each category

select 
	category as Category ,
	avg(cost) as Average_Cost
from gold.dim_products
group by category
order by Average_Cost desc
--what is the total revenue generated for each category
select category as Category ,sum(sales_amount) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by Revenue desc
--what is the total revenue generated by each customer?

select c.customer_key as Customer_key ,sum(sales_amount) as Revenue,concat(c.first_name,',',c.last_name) as Customer_name
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,concat(c.first_name,',',c.last_name)
order by Revenue desc

select c.country as Country ,sum(quantity) as Quantity
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by Quantity desc
--Which age group generated the most revenue	
select
sum(sales_amount) as Revenue,
 case 
	when year(getdate())-year(birthdate) <20 then 'young'
	when year(getdate())-year(birthdate) between 20 and 40 then 'old'
	else 'too_old ' 
	end as age
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key=f.customer_key
group by 
case 
	when year(getdate())-year(birthdate) <20 then 'young'
	when year(getdate())-year(birthdate) between 20 and 40 then 'old'
	else 'too_old ' 
	end 
order by Revenue desc

--%contribution of each product category to the total revenue

select 
	p.category as Category ,
	round((SUM(f.sales_amount) * 100.0 /
        (SELECT SUM(sales_amount) FROM gold.fact_sales)),2) AS revenue_contribution
from gold.dim_products p
left join gold.fact_sales f
on f.product_key=p.product_key
group by category
order by revenue_contribution desc


--which top  5 products generate the highest revenue


select top 5  p.product_name as Product_Name ,sum(sales_amount) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name
order by Revenue desc
--what are the  5 worst products generate in terms of the sales
select top 5  p.product_name as Product_Name ,sum(sales_amount) as Revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name
order by Revenue ;

--what are the  5 top products generate in terms of the Revenue
select * from

(
select  p.product_name as Product_Name ,sum(sales_amount) as Revenue,

row_number() over (order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name) t
where rank_products <=5

--Find the top 10 customers who have generated the highest revenue
select top 10 c.customer_key as Customer_key ,sum(sales_amount) as Revenue,concat(c.first_name,',',c.last_name) as Customer_name
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,concat(c.first_name,',',c.last_name)
order by Revenue desc

select * from
(
select  c.customer_key as Customer_key ,sum(sales_amount) as Revenue,concat(c.first_name,',',c.last_name) as Customer_name,
row_number() over (order by sum(f.sales_amount) desc) as Rank_customers
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,concat(c.first_name,',',c.last_name) ) t 
where Rank_customers<=5

--Find the 3 customers with the fewest orders placed

select top 3 c.customer_key as Customer_key ,sum(quantity) as Quantity
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key
order by Quantity 